import 'package:flutter/material.dart';
import '../services/inventory_service.dart';
import '../models/inventory_model.dart';
import '../services/analytics_service.dart';

class AddItemScreen extends StatefulWidget {
  const AddItemScreen({Key? key}) : super(key: key);

  @override
  State<AddItemScreen> createState() => _AddItemScreenState();
}

class _AddItemScreenState extends State<AddItemScreen> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _qtyController = TextEditingController();
  final _priceController = TextEditingController();
  final _minStockController = TextEditingController();
  final _descController = TextEditingController();
  
  bool _isLoading = false;
  final InventoryService _inventoryService = InventoryService();

  void _submit() async {
    if (_formKey.currentState!.validate()) {
      setState(() => _isLoading = true);
      
      final newItem = InventoryModel(
        itemId: 0, // Auto-generated by DB
        itemName: _nameController.text,
        quantity: int.parse(_qtyController.text),
        categoryName: 'Electronics', // Default for now
        locationName: 'Warehouse A', // Default for now
        conditionStatus: 'Good',
        minStock: int.parse(_minStockController.text),
        unitPrice: double.parse(_priceController.text),
        description: _descController.text,
      );

      // Hardcoded userId = 1 for now, or fetch from auth service
      final success = await _inventoryService.addItem(newItem, 1);

      setState(() => _isLoading = false);

      if (success) {
        await AnalyticsService.logInventoryAction(
          action: 'add_item', 
          itemId: 'new', 
          itemName: newItem.itemName
        );
        
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Item berhasil ditambahkan')),
          );
          Navigator.pop(context, true); // Return true to refresh list
        }
      } else {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Gagal menambahkan item')),
          );
        }
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFF0F1419),
      appBar: AppBar(
        backgroundColor: const Color(0xFF1A2332),
        title: const Text('Tambah Item Baru', style: TextStyle(color: Colors.white)),
        iconTheme: const IconThemeData(color: Colors.white),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              _buildTextField('Nama Item', _nameController),
              const SizedBox(height: 16),
              Row(
                children: [
                  Expanded(child: _buildTextField('Jumlah', _qtyController, isNumber: true)),
                  const SizedBox(width: 16),
                  Expanded(child: _buildTextField('Min. Stok', _minStockController, isNumber: true)),
                ],
              ),
              const SizedBox(height: 16),
              _buildTextField('Harga Satuan', _priceController, isNumber: true),
              const SizedBox(height: 16),
              _buildTextField('Deskripsi', _descController, maxLines: 3),
              const SizedBox(height: 32),
              SizedBox(
                width: double.infinity,
                child: ElevatedButton(
                  onPressed: _isLoading ? null : _submit,
                  style: ElevatedButton.styleFrom(
                    backgroundColor: Colors.blue,
                    padding: const EdgeInsets.symmetric(vertical: 16),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                  ),
                  child: _isLoading 
                    ? const SizedBox(height: 20, width: 20, child: CircularProgressIndicator(color: Colors.white, strokeWidth: 2))
                    : const Text('Simpan Item', style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold, color: Colors.white)),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildTextField(String label, TextEditingController controller, {bool isNumber = false, int maxLines = 1}) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(label, style: const TextStyle(color: Colors.grey, fontSize: 12)),
        const SizedBox(height: 8),
        TextFormField(
          controller: controller,
          keyboardType: isNumber ? TextInputType.number : TextInputType.text,
          maxLines: maxLines,
          style: const TextStyle(color: Colors.white),
          validator: (value) => value == null || value.isEmpty ? 'Wajib diisi' : null,
          decoration: InputDecoration(
            filled: true,
            fillColor: const Color(0xFF1A2332),
            border: OutlineInputBorder(borderRadius: BorderRadius.circular(8), borderSide: BorderSide.none),
            contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
          ),
        ),
      ],
    );
  }
}
